language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ben.gu.au@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: QrJAPFf0ozzpX2XYVDsn0uiI9qV+apntrA08Z1LNTAEkQwjyCrZvS0LAVp+gbizmnwHH42BzFEkbJnEqeoSfgVTVrfUSbVAOu6dnqdopsHNUi5LXfNzfjU9UoR9uL1T9BxR41b1GSu9CziD3DQoxweGpmbrhn+sscPX0f2p4jhLAi1jjoYZrQui64EhlIukXtzdBee/bxGItboDnAh+E5AR8xIUGdr9pt45MEIVceALV3BZgaYlxcBmhLailiKkx+Gbv42lxM2LGzc1fZEuW/7l29FMYdttjdVglQoj95od5MLd6xz+HbISyFDRT34aVu3tI8Yz3kDjdK/XJF5sqTBpBS42XUiPJhQrTuR3w2E3R68/Yie+nWogjotMGSUYc1nUA0hV+zb9nc8z/yd3Dqt5UusZbXuwAgPyXJ59TcgXtmD0VuQIcaemDBgRA4xOyywSyoPT2LGDMlDT6o2w3uBNJMKjSz60Ol2kpB323e9iOIMUwTe/30J/k9tzwy2Jhs8Gjd3vOoUuKQ8+PCEYD6/yAsMX+i45/lGq5DmRwKOz+GCvisyDV+9uPzGIY1huKR8eLganBhVYZMNZbpHNTXFfjTf17aaE2IhN6aTuciErJcoIQ/nivfDe5Y33IOpWDdn0K0Td9N69jQcI4Gf2jl19L2eJLy7bLxZpQ6CjDwhA=
  - secure: q/2FcNjXqlODrLvhVRQZF/LFqoRcHj9wJMPOjIZ8GDpdVXQGhXuccKnpJEke9A43v2Oe78jBWOJxg8vd7Go2EcTz/OD5miPaPsYl/1jkXY90gpbw3DQNTQDq7vmbB6n82WhiXzOh7ZP0WiPMWtnZw7uynWAG9WB4QrGKUIURyKh7qy8EVkoxjXT3wgAdW+T/wpB6YCopIwOlMaQLOyAz6AhO9Gj+Vpe9Wt3fZUbzqpeDNd0e0oRGf8kZg+GPKQr3K9htvcwSVBL9yGjcV7RX/rvNpfgeLjInVHQZJ+wZHI07E0aiJjlC54wfO+lwT/eqN73jnCIiufelWun++F3wbyXNMxT1kQB6nvWknJkK8WzHygB6V9c1A/exN+drIUFdbttdqy1NjHgUyKhtT3qzeb+SXd2gRz0maCeDhNMgofr2vTf5kNypVpkaTsoUJ8dfE5e7kwMLCsvAQYprCkAQ6jhp1FbIsCd6OVPuxSTHmGglR4vDj2XBZeOI1D5JJHwDTFk1dFwgsWPMnWRGqBw6FctwylDhUAHJhYgtYsm2ofUoS9vZxUdLyCb9ZgyDNzQoektTVCCD1tEM49HaKPVqVDY2qBVtDP4AiGC5ZGX6sbH2SzhFKytqKWafS39r2dXFxrf0NJGp+/KrwOmWe72+VSGmuOR0RdLPBu/U9ng2NEE=
  - secure: HsijYZJfrFXsea939TpvQXJMIXNAj7PfqXp2skYR7shrStof0w3CoKlnDCN/8EHtlfVnXnw1YegVw85evVHT3BUpW/IHwYLTC2+N3VW7PveriQ7+lSuYVRuoG7bRlkKRPa7WYjIVnqsuKdk8h/RCr1u4AGTmjL5p3Wgqbp+vpesn5wZBaaU+HH7m6Ul00jJd8OqRXYprTbrt+Taby7t9ImZ3nw6alw1eEVG4l0rQeZrSAz3lqco0IS7Zj7w0pvSRsO1aPSz5zZpzjLRTqFjyz/D5cx194DBaL8GP7erXrF7GiMGiR2C/OE2M3mfrmcILZbm8+35k/mY3VotWGCkItCBzYwXY8K4qxDdgdFcG+gz3sQ1+Q4rYDQieXqHJY8pZsY4/+sOwxvlDSZmbBjM2tc56Yr/LntHrxhQuW7JJi7ZA/1PR8d5zgko80djJL6fVKIPG9Se3VFFqGZk8KMCxsliQkcsNsXKlsDEdHJUMvh3NKyQrvqOEcZF/mgIM8cX+6lt90GKBiSdu+52shq92CEd/lCKNxGbUHRsXX56q2jfrNT/OXiIqEsXVkb66AuSy21O/S0fr5qWa/ElgdBbHIRfSFrxIjRfwZt0C5FOikybSmvtZTcDvtraXzQJ1wCAZ6op7r8NQuuQ3VHTVrUYJS5QAp//NUKUaC89B2H+4LZM=
  - secure: PH1XrZsGtZ4cQHsezdapQT8JedXzd+VxWBC7aTadqgU27Sq1wH7dJIIpryrgpIEVESwv5BBbSqKWMAWxPJP9eEYJY3iRi4pbX4ShJwZWlV55VN1KDaAc7YMLH71MbASFA2byyEDFIA/wArcPWZ/P638sr23xVqq9bxofKTnGqrgw9+R9vDhiSu+TPXD6znZQz6s+TSUtb5eRvNSl/29mW+fsoaj21a9hpe5h3IFN9ph3y4u3im2gMA8ldQbyal3CJI0yu3xUGQseHiuVwkOGnmjIjN6OWJgcDswfoWiy6zZ5/q0WetnpqA/+M0Y42sRw08fCXvHsgzALMq2jRo2awxuUvmyOY1g3fGzTYd5e42gl1zsnp+tqKLQ4AxsrUbI2SXOxFWFNXLBCm9Byt1iu9kIv/G3NJVirvIv1BmXtPYUFEoBHHasmOFhcu4LFZVZPKNSJe+7yFzydJV+PHTLD3eEVkUuml32dQTxpUXMwNQwI+t9BcF9W+dpCA+Dsc6pGj9GzcLo9LGBtkODDG86e1X3GCjmOhuMxpZESbRhtuDg1erZscJ2R7aoB4bWE2x63+/vkdtvhEWYwhSYjaWYE35r0BFA42M9NTJFzBJiaAL7w2Hki3MPvlJYzJka3jS2EacAQh9zxbF6OcnbC5uwZ8MAF0CYu8zljODyqEakjsyg=
  - secure: voHuGKSmL1DZBAL0XKXK78pWdSTuVTheR0LHzcZyA6JBnSCkeNkZEjgEjRn+y7WjihXHUR2HyrTyC7Z4hCoFlP7VkWvbPcbfSNcMHo/DtvmKuhRgs9tFswD9jLgALXtc/TZUL3jiREHEdrFrKhoqO7GCV/8HFY+wLKzKrjQaejF+5D/Q4CCbgfbcWHhiGtUVIYt1o9U9FLRljML8ZX1Ws/NIqHA0envsytsa4cUylMPkVGMOgwljV5+w8mNteAE5pNB4ye6YxL0Kiq64SGBBwMkp/JmLFoX29EM+qhpe9y7khAGHTtXlzrlRiorUKibgdyXmKHATF35gG2ZFk0oNmqdPe2JvBakXJuTGXFsQs9BTHiEtzvrpqilb6IsNtAEOEDPBeTDUYUHAcZUkOvm+BsKOpnhWwkV2QGfi3KOJjK6rGUjc8MC3rZ139NX5mIQyi+9arWY0uSvaGBiWlzYql+eEqslNM5pOMySru9uI0QNJdasE+8nn3bjFd67PQxEFT6i1ZJGayJZrSoZkc2ZkSIesT0hF0ZIL0IXVI5pq7BYCMFve/Dd3g6NRPZIUlulgo8VggBYa8REpw+pLJ8ueFn8OVOR9YNGRSeJ+wLURuoDihXeypdx7xJWLBYD2LpGZC2RIdmwoBZfE9QhjuNRyHkwPL4vs9tHVEBsv0ZueVGA=
before_install:
- gem install travis -v 1.8.5 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=54.215.193.139
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
